### ISSUE TITLE
OP_RETURN utility fails with Internal Server Error

### ISSUE THREAD

**Issue by shesek** [valerio-vaccaro/liquidtestnet.com#1]
Can be seen here: https://liquidtestnet.com/utils?command=opreturn&text=test&action=send

Thank you for building liquidtestnet.com, it's very useful!

**Comment by valerio-vaccaro** [comment]
Tnx! I will add an error if you don't pass an hex string and maybe an option to convert an ascii string to hex

**Comment by shesek** [comment]
Oh, sorry, I totally missed that it was asking for a hex string (despite the page saying it clearly). It works when I input one. Would be useful if the error was more explicit.
