### ISSUE TITLE
How is liquid mined?

### ISSUE THREAD

**Issue by jomagalo** [valerio-vaccaro/liquidtestnet.com#14]
Hello,

I have set up a liquid node (liquidtestnet). I want to mine some blocks to get some coins, but I can't find a way. Could you tell me how to proceed? 

I have tried this:
`elements-cli rescanblockchain`
`elements-cli generatetoaddress 11 myaddr`

`Unable to fill out dynamic federation signblockscript witness, are you sure it's WSH(OP_TRUE)?`

Is there a similar way or another procedure to create liquid in testnet?

Thank you

**Comment by levantah** [comment]
Not possible.

If you could mine it would be slightly similar to mining on a custom Bitcoin signet but there even if very low difficulty and permissioned, one still mines but on Liquid (incl. liquidtestnet) the blocks are just made and signed.

Read more at https://elementsproject.org
