### ISSUE TITLE
Lower fees

### ISSUE THREAD

**Issue by levantah** [valerio-vaccaro/liquidtestnet.com#16]
Hi @valerio-vaccaro !

Please set the mining node(s) to include 0.01 sat/vB transactions into blocks. On Bitcoin signet it would be done by adding following to config:

```
mintxfee=0.0000001
blockmintxfee=0.0000001
minrelaytxfee=0.0000001
incrementalrelayfee=0.0000001
```

And send me some liquidtestnet coins to `tlq1qqt23pvucnjcefy942y072eu73gd0773pja295m7z508xdmuhymfx08kd8y37y7469dg6neneuweeftsqm2djyujft3dn0s324` please. I would like to run an alternative faucet.

Thank you for running the liquid testnetfaucet!

**Comment by valerio-vaccaro** [comment]
Now I implemented CT discount on faucet
